pipeline:
  agent:
    any
  stages:
    - stage: "Clonar Repositorio"
      steps:
        - sh: "echo 'Clonando el repositorio...'"
    - stage: "Construir"
      steps:
        - sh: "echo 'Construyendo el proyecto...'"
    - stage: "Pruebas"
      steps:
        - sh: "echo 'Ejecutando pruebas...'"
    - stage: "Desplegar"
      steps:
        - sh: "echo 'Desplegando el proyecto...'"
  post:
    success:
      - sh: "echo '¡Pipeline ejecutado exitosamente!'"
    failure:
      - sh: "echo '¡Pipeline fallido! Se requiere acción.'"
